name: Debug Hackatime API

on:
  workflow_dispatch: # Manual trigger only

jobs:
  debug-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install markscribe from taciturnaxolotl fork
        run: |
          git clone https://github.com/taciturnaxolotl/markscribe.git
          cd markscribe
          go build -o markscribe .
          sudo mv markscribe /usr/local/bin/

      - name: Test API Connection
        run: |
          echo "=== Testing Hackatime API Connection ==="
          markscribe -write debug-output.md debug-api.tpl
          echo "=== Debug Output ==="
          cat debug-output.md
          echo "=== End Debug Output ==="
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_URL: "https://hackatime.hackclub.com/api/compat/wakatime/v1"

      - name: Upload debug output
        uses: actions/upload-artifact@v3
        with:
          name: hackatime-debug-output
          path: debug-output.md
        if: always()
