name: Test Fixed Template

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install and patch markscribe for Hackatime Bearer auth
        run: |
          git clone https://github.com/taciturnaxolotl/markscribe.git
          cd markscribe

          # Patch wakatime.go to use Bearer auth instead of Basic auth
          sed -i 's/req\.Header\.Set("Authorization", fmt\.Sprintf("Basic %s", wakatimeClient\.apikey))/req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", wakatimeClient.apikey))/' wakatime.go

          go build -o markscribe .
          sudo mv markscribe /usr/local/bin/

      - name: Test Fixed Template
        run: |
          echo "=== Testing Fixed Template ==="
          markscribe -write test-output.md README-complete.md.tpl
          echo "=== Test Output ==="
          cat test-output.md
          echo "=== End Test Output ==="
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_URL: "https://hackatime.hackclub.com/api/hackatime/v1"

      - name: Show Math Check
        run: |
          echo ""
          echo "=== MATH VERIFICATION ==="
          echo "Check if the total time in the output above matches the sum of project times"
          echo "Check if all languages and projects are shown and if they add up to 9h 17m total"

      - name: Upload test output
        uses: actions/upload-artifact@v3
        with:
          name: template-test-output
          path: test-output.md
        if: always()
