name: Waka Readme (Anmol098)

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [main]

jobs:
  update-readme:
    name: Update README with stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_URL: "https://hackatime.hackclub.com/api/compat/wakatime/v1"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_COMMIT: "True"

          # Customization options
          COMMIT_MESSAGE: "📊 Updated development metrics"
          SHOW_TOTAL_CODE_TIME: "True"
          LOCALE: "en"

          # Display options - adjust these as needed
          BARS_GRAPH_TYPE: "flat"
          SHOW_LANGUAGE: "True"
          SHOW_WAKA_STATS: "True"
